// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Virt
{
    public static class GetClusterType
    {
        public static Task<GetClusterTypeResult> InvokeAsync(GetClusterTypeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetClusterTypeResult>("netbox:virt/getClusterType:getClusterType", args ?? new GetClusterTypeArgs(), options.WithDefaults());

        public static Output<GetClusterTypeResult> Invoke(GetClusterTypeInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetClusterTypeResult>("netbox:virt/getClusterType:getClusterType", args ?? new GetClusterTypeInvokeArgs(), options.WithDefaults());

        public static Output<GetClusterTypeResult> Invoke(GetClusterTypeInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetClusterTypeResult>("netbox:virt/getClusterType:getClusterType", args ?? new GetClusterTypeInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetClusterTypeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetClusterTypeArgs()
        {
        }
        public static new GetClusterTypeArgs Empty => new GetClusterTypeArgs();
    }

    public sealed class GetClusterTypeInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetClusterTypeInvokeArgs()
        {
        }
        public static new GetClusterTypeInvokeArgs Empty => new GetClusterTypeInvokeArgs();
    }


    [OutputType]
    public sealed class GetClusterTypeResult
    {
        public readonly int ClusterTypeId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetClusterTypeResult(
            int clusterTypeId,

            string id,

            string name)
        {
            ClusterTypeId = clusterTypeId;
            Id = id;
            Name = name;
        }
    }
}
