// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Ipam
{
    public static class GetPrefixes
    {
        public static Task<GetPrefixesResult> InvokeAsync(GetPrefixesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPrefixesResult>("netbox:ipam/getPrefixes:getPrefixes", args ?? new GetPrefixesArgs(), options.WithDefaults());

        public static Output<GetPrefixesResult> Invoke(GetPrefixesInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrefixesResult>("netbox:ipam/getPrefixes:getPrefixes", args ?? new GetPrefixesInvokeArgs(), options.WithDefaults());

        public static Output<GetPrefixesResult> Invoke(GetPrefixesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrefixesResult>("netbox:ipam/getPrefixes:getPrefixes", args ?? new GetPrefixesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrefixesArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetPrefixesFilterArgs>? _filters;

        /// <summary>
        /// A list of filters to apply to the API query when requesting prefixes.
        /// </summary>
        public List<Inputs.GetPrefixesFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetPrefixesFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// The limit of objects to return from the API lookup. Defaults to `0`.
        /// </summary>
        [Input("limit")]
        public int? Limit { get; set; }

        public GetPrefixesArgs()
        {
        }
        public static new GetPrefixesArgs Empty => new GetPrefixesArgs();
    }

    public sealed class GetPrefixesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private InputList<Inputs.GetPrefixesFilterInputArgs>? _filters;

        /// <summary>
        /// A list of filters to apply to the API query when requesting prefixes.
        /// </summary>
        public InputList<Inputs.GetPrefixesFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetPrefixesFilterInputArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// The limit of objects to return from the API lookup. Defaults to `0`.
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        public GetPrefixesInvokeArgs()
        {
        }
        public static new GetPrefixesInvokeArgs Empty => new GetPrefixesInvokeArgs();
    }


    [OutputType]
    public sealed class GetPrefixesResult
    {
        /// <summary>
        /// A list of filters to apply to the API query when requesting prefixes.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPrefixesFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The limit of objects to return from the API lookup. Defaults to `0`.
        /// </summary>
        public readonly int? Limit;
        public readonly ImmutableArray<Outputs.GetPrefixesPrefixResult> Prefixes;

        [OutputConstructor]
        private GetPrefixesResult(
            ImmutableArray<Outputs.GetPrefixesFilterResult> filters,

            string id,

            int? limit,

            ImmutableArray<Outputs.GetPrefixesPrefixResult> prefixes)
        {
            Filters = filters;
            Id = id;
            Limit = limit;
            Prefixes = prefixes;
        }
    }
}
