// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Ipam
{
    /// <summary>
    /// From the [official documentation](https://docs.netbox.dev/en/stable/features/ipam/#ip-addresses):
    /// 
    /// &gt; An IP address comprises a single host address (either IPv4 or IPv6) and its subnet mask. Its mask should match exactly how the IP address is configured on an interface in the real world.
    /// &gt; 
    /// &gt; Like a prefix, an IP address can optionally be assigned to a VRF (otherwise, it will appear in the "global" table). IP addresses are automatically arranged under parent prefixes within their respective VRFs according to the IP hierarchy.
    /// 
    /// ## Example Usage
    /// 
    /// ### Creating an IP address that is assigned to a virtual machine interface
    /// 
    /// Starting with provider version 3.5.0, you can use the `virtual_machine_interface_id` attribute to assign an IP address to a virtual machine interface.
    /// You can also use the `interface_id` and `object_type` attributes instead.
    /// 
    /// With `virtual_machine_interface_id`:
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Netbox = Pulumi.Netbox;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Assuming a virtual machine with the id `123` exists
    ///     var @this = new Netbox.Virt.Interface("this", new()
    ///     {
    ///         Name = "eth0",
    ///         VirtualMachineId = 123,
    ///     });
    /// 
    ///     var thisIpAddress = new Netbox.Ipam.IpAddress("this", new()
    ///     {
    ///         Address = "10.0.0.60/24",
    ///         Status = "active",
    ///         VirtualMachineInterfaceId = @this.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// With `object_type` and `interface_id`:
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Netbox = Pulumi.Netbox;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Assuming a virtual machine with the id `123` exists
    ///     var @this = new Netbox.Virt.Interface("this", new()
    ///     {
    ///         Name = "eth0",
    ///         VirtualMachineId = 123,
    ///     });
    /// 
    ///     var thisIpAddress = new Netbox.Ipam.IpAddress("this", new()
    ///     {
    ///         Address = "10.0.0.60/24",
    ///         Status = "active",
    ///         InterfaceId = @this.Id,
    ///         ObjectType = "virtualization.vminterface",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Creating an IP address that is assigned to a device interface
    /// 
    /// Starting with provider version 3.5.0, you can use the `device_interface_id` attribute to assign an IP address to a device interface.
    /// You can also use the `interface_id` and `object_type` attributes instead.
    /// 
    /// With `device_interface_id`:
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Netbox = Pulumi.Netbox;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Assuming a device with the id `123` exists
    ///     var @this = new Netbox.Dcim.DeviceInterface("this", new()
    ///     {
    ///         Name = "eth0",
    ///         DeviceId = 123,
    ///         Type = "1000base-t",
    ///     });
    /// 
    ///     var thisIpAddress = new Netbox.Ipam.IpAddress("this", new()
    ///     {
    ///         Address = "10.0.0.60/24",
    ///         Status = "active",
    ///         DeviceInterfaceId = @this.Id,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// With `object_type` and `interface_id`:
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Netbox = Pulumi.Netbox;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Assuming a device with the id `123` exists
    ///     var @this = new Netbox.Dcim.DeviceInterface("this", new()
    ///     {
    ///         Name = "eth0",
    ///         DeviceId = 123,
    ///         Type = "1000base-t",
    ///     });
    /// 
    ///     var thisIpAddress = new Netbox.Ipam.IpAddress("this", new()
    ///     {
    ///         Address = "10.0.0.60/24",
    ///         Status = "active",
    ///         InterfaceId = @this.Id,
    ///         ObjectType = "dcim.interface",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Creating an IP address that is not assigned to anything
    /// 
    /// You can create an IP address that is not assigend to anything by omitting the attributes mentioned above.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Netbox = Pulumi.Netbox;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var @this = new Netbox.Ipam.IpAddress("this", new()
    ///     {
    ///         Address = "10.0.0.50/24",
    ///         Status = "reserved",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [NetboxResourceType("netbox:ipam/ipAddress:IpAddress")]
    public partial class IpAddress : global::Pulumi.CustomResource
    {
        [Output("customFields")]
        public Output<ImmutableDictionary<string, string>?> CustomFields { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Conflicts with `interface_id` and `virtual_machine_interface_id`.
        /// </summary>
        [Output("deviceInterfaceId")]
        public Output<int?> DeviceInterfaceId { get; private set; } = null!;

        [Output("dnsName")]
        public Output<string?> DnsName { get; private set; } = null!;

        /// <summary>
        /// Required when `object_type` is set.
        /// </summary>
        [Output("interfaceId")]
        public Output<int?> InterfaceId { get; private set; } = null!;

        [Output("ipAddress")]
        public Output<string> Address { get; private set; } = null!;

        [Output("natInsideAddressId")]
        public Output<int?> NatInsideAddressId { get; private set; } = null!;

        [Output("natOutsideAddresses")]
        public Output<ImmutableArray<Outputs.IpAddressNatOutsideAddress>> NatOutsideAddresses { get; private set; } = null!;

        /// <summary>
        /// Valid values are `virtualization.vminterface` and `dcim.interface`. Required when `interface_id` is set.
        /// </summary>
        [Output("objectType")]
        public Output<string?> ObjectType { get; private set; } = null!;

        /// <summary>
        /// Valid values are `loopback`, `secondary`, `anycast`, `vip`, `vrrp`, `hsrp`, `glbp` and `carp`.
        /// </summary>
        [Output("role")]
        public Output<string?> Role { get; private set; } = null!;

        /// <summary>
        /// Valid values are `active`, `reserved`, `deprecated`, `dhcp` and `slaac`.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        [Output("tenantId")]
        public Output<int?> TenantId { get; private set; } = null!;

        /// <summary>
        /// Conflicts with `interface_id` and `device_interface_id`.
        /// </summary>
        [Output("virtualMachineInterfaceId")]
        public Output<int?> VirtualMachineInterfaceId { get; private set; } = null!;

        [Output("vrfId")]
        public Output<int?> VrfId { get; private set; } = null!;


        /// <summary>
        /// Create a IpAddress resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IpAddress(string name, IpAddressArgs args, CustomResourceOptions? options = null)
            : base("netbox:ipam/ipAddress:IpAddress", name, args ?? new IpAddressArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IpAddress(string name, Input<string> id, IpAddressState? state = null, CustomResourceOptions? options = null)
            : base("netbox:ipam/ipAddress:IpAddress", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/NatzkaLabsOpenSource/pulumi-netbox",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IpAddress resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IpAddress Get(string name, Input<string> id, IpAddressState? state = null, CustomResourceOptions? options = null)
        {
            return new IpAddress(name, id, state, options);
        }
    }

    public sealed class IpAddressArgs : global::Pulumi.ResourceArgs
    {
        [Input("customFields")]
        private InputMap<string>? _customFields;
        public InputMap<string> CustomFields
        {
            get => _customFields ?? (_customFields = new InputMap<string>());
            set => _customFields = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Conflicts with `interface_id` and `virtual_machine_interface_id`.
        /// </summary>
        [Input("deviceInterfaceId")]
        public Input<int>? DeviceInterfaceId { get; set; }

        [Input("dnsName")]
        public Input<string>? DnsName { get; set; }

        /// <summary>
        /// Required when `object_type` is set.
        /// </summary>
        [Input("interfaceId")]
        public Input<int>? InterfaceId { get; set; }

        [Input("ipAddress", required: true)]
        public Input<string> Address { get; set; } = null!;

        [Input("natInsideAddressId")]
        public Input<int>? NatInsideAddressId { get; set; }

        /// <summary>
        /// Valid values are `virtualization.vminterface` and `dcim.interface`. Required when `interface_id` is set.
        /// </summary>
        [Input("objectType")]
        public Input<string>? ObjectType { get; set; }

        /// <summary>
        /// Valid values are `loopback`, `secondary`, `anycast`, `vip`, `vrrp`, `hsrp`, `glbp` and `carp`.
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// Valid values are `active`, `reserved`, `deprecated`, `dhcp` and `slaac`.
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        [Input("tags")]
        private InputList<string>? _tags;
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tenantId")]
        public Input<int>? TenantId { get; set; }

        /// <summary>
        /// Conflicts with `interface_id` and `device_interface_id`.
        /// </summary>
        [Input("virtualMachineInterfaceId")]
        public Input<int>? VirtualMachineInterfaceId { get; set; }

        [Input("vrfId")]
        public Input<int>? VrfId { get; set; }

        public IpAddressArgs()
        {
        }
        public static new IpAddressArgs Empty => new IpAddressArgs();
    }

    public sealed class IpAddressState : global::Pulumi.ResourceArgs
    {
        [Input("customFields")]
        private InputMap<string>? _customFields;
        public InputMap<string> CustomFields
        {
            get => _customFields ?? (_customFields = new InputMap<string>());
            set => _customFields = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Conflicts with `interface_id` and `virtual_machine_interface_id`.
        /// </summary>
        [Input("deviceInterfaceId")]
        public Input<int>? DeviceInterfaceId { get; set; }

        [Input("dnsName")]
        public Input<string>? DnsName { get; set; }

        /// <summary>
        /// Required when `object_type` is set.
        /// </summary>
        [Input("interfaceId")]
        public Input<int>? InterfaceId { get; set; }

        [Input("ipAddress")]
        public Input<string>? Address { get; set; }

        [Input("natInsideAddressId")]
        public Input<int>? NatInsideAddressId { get; set; }

        [Input("natOutsideAddresses")]
        private InputList<Inputs.IpAddressNatOutsideAddressGetArgs>? _natOutsideAddresses;
        public InputList<Inputs.IpAddressNatOutsideAddressGetArgs> NatOutsideAddresses
        {
            get => _natOutsideAddresses ?? (_natOutsideAddresses = new InputList<Inputs.IpAddressNatOutsideAddressGetArgs>());
            set => _natOutsideAddresses = value;
        }

        /// <summary>
        /// Valid values are `virtualization.vminterface` and `dcim.interface`. Required when `interface_id` is set.
        /// </summary>
        [Input("objectType")]
        public Input<string>? ObjectType { get; set; }

        /// <summary>
        /// Valid values are `loopback`, `secondary`, `anycast`, `vip`, `vrrp`, `hsrp`, `glbp` and `carp`.
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// Valid values are `active`, `reserved`, `deprecated`, `dhcp` and `slaac`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        [Input("tenantId")]
        public Input<int>? TenantId { get; set; }

        /// <summary>
        /// Conflicts with `interface_id` and `device_interface_id`.
        /// </summary>
        [Input("virtualMachineInterfaceId")]
        public Input<int>? VirtualMachineInterfaceId { get; set; }

        [Input("vrfId")]
        public Input<int>? VrfId { get; set; }

        public IpAddressState()
        {
        }
        public static new IpAddressState Empty => new IpAddressState();
    }
}
