// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getTenantGroup(args: GetTenantGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbox:tenancy/getTenantGroup:getTenantGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantGroup.
 */
export interface GetTenantGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getTenantGroup.
 */
export interface GetTenantGroupResult {
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly parentId: number;
    readonly slug: string;
}
export function getTenantGroupOutput(args: GetTenantGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTenantGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbox:tenancy/getTenantGroup:getTenantGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenantGroup.
 */
export interface GetTenantGroupOutputArgs {
    name: pulumi.Input<string>;
}
