// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as netbox from "@natzka-oss/pulumi-netbox";
 *
 * const customerA = netbox.tenancy.getTenant({
 *     name: "Customer A",
 * });
 * ```
 */
export function getTenant(args?: GetTenantArgs, opts?: pulumi.InvokeOptions): Promise<GetTenantResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbox:tenancy/getTenant:getTenant", {
        "description": args.description,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenant.
 */
export interface GetTenantArgs {
    description?: string;
    /**
     * At least one of `name` or `slug` must be given.
     */
    name?: string;
    /**
     * At least one of `name` or `slug` must be given.
     */
    slug?: string;
}

/**
 * A collection of values returned by getTenant.
 */
export interface GetTenantResult {
    readonly description?: string;
    readonly groupId: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * At least one of `name` or `slug` must be given.
     */
    readonly name: string;
    /**
     * At least one of `name` or `slug` must be given.
     */
    readonly slug: string;
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as netbox from "@natzka-oss/pulumi-netbox";
 *
 * const customerA = netbox.tenancy.getTenant({
 *     name: "Customer A",
 * });
 * ```
 */
export function getTenantOutput(args?: GetTenantOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTenantResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbox:tenancy/getTenant:getTenant", {
        "description": args.description,
        "name": args.name,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getTenant.
 */
export interface GetTenantOutputArgs {
    description?: pulumi.Input<string>;
    /**
     * At least one of `name` or `slug` must be given.
     */
    name?: pulumi.Input<string>;
    /**
     * At least one of `name` or `slug` must be given.
     */
    slug?: pulumi.Input<string>;
}
