// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Dcim
{
    public static class GetPlatform
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Netbox = Pulumi.Netbox;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var PANOS = Netbox.Dcim.GetPlatform.Invoke(new()
        ///     {
        ///         Name = "PANOS",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetPlatformResult> InvokeAsync(GetPlatformArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPlatformResult>("netbox:dcim/getPlatform:getPlatform", args ?? new GetPlatformArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Netbox = Pulumi.Netbox;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var PANOS = Netbox.Dcim.GetPlatform.Invoke(new()
        ///     {
        ///         Name = "PANOS",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPlatformResult> Invoke(GetPlatformInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlatformResult>("netbox:dcim/getPlatform:getPlatform", args ?? new GetPlatformInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Netbox = Pulumi.Netbox;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var PANOS = Netbox.Dcim.GetPlatform.Invoke(new()
        ///     {
        ///         Name = "PANOS",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetPlatformResult> Invoke(GetPlatformInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlatformResult>("netbox:dcim/getPlatform:getPlatform", args ?? new GetPlatformInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPlatformArgs : global::Pulumi.InvokeArgs
    {
        [Input("manufacturerId")]
        public int? ManufacturerId { get; set; }

        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetPlatformArgs()
        {
        }
        public static new GetPlatformArgs Empty => new GetPlatformArgs();
    }

    public sealed class GetPlatformInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("manufacturerId")]
        public Input<int>? ManufacturerId { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetPlatformInvokeArgs()
        {
        }
        public static new GetPlatformInvokeArgs Empty => new GetPlatformInvokeArgs();
    }


    [OutputType]
    public sealed class GetPlatformResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int? ManufacturerId;
        public readonly string Name;
        public readonly string Slug;

        [OutputConstructor]
        private GetPlatformResult(
            string id,

            int? manufacturerId,

            string name,

            string slug)
        {
            Id = id;
            ManufacturerId = manufacturerId;
            Name = name;
            Slug = slug;
        }
    }
}
