// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Dcim
{
    public static class GetRacks
    {
        public static Task<GetRacksResult> InvokeAsync(GetRacksArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRacksResult>("netbox:dcim/getRacks:getRacks", args ?? new GetRacksArgs(), options.WithDefaults());

        public static Output<GetRacksResult> Invoke(GetRacksInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRacksResult>("netbox:dcim/getRacks:getRacks", args ?? new GetRacksInvokeArgs(), options.WithDefaults());

        public static Output<GetRacksResult> Invoke(GetRacksInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRacksResult>("netbox:dcim/getRacks:getRacks", args ?? new GetRacksInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRacksArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private List<Inputs.GetRacksFilterArgs>? _filters;
        public List<Inputs.GetRacksFilterArgs> Filters
        {
            get => _filters ?? (_filters = new List<Inputs.GetRacksFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// Defaults to `0`.
        /// </summary>
        [Input("limit")]
        public int? Limit { get; set; }

        public GetRacksArgs()
        {
        }
        public static new GetRacksArgs Empty => new GetRacksArgs();
    }

    public sealed class GetRacksInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("filters")]
        private InputList<Inputs.GetRacksFilterInputArgs>? _filters;
        public InputList<Inputs.GetRacksFilterInputArgs> Filters
        {
            get => _filters ?? (_filters = new InputList<Inputs.GetRacksFilterInputArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// Defaults to `0`.
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        public GetRacksInvokeArgs()
        {
        }
        public static new GetRacksInvokeArgs Empty => new GetRacksInvokeArgs();
    }


    [OutputType]
    public sealed class GetRacksResult
    {
        public readonly ImmutableArray<Outputs.GetRacksFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Defaults to `0`.
        /// </summary>
        public readonly int? Limit;
        public readonly ImmutableArray<Outputs.GetRacksRackResult> Racks;

        [OutputConstructor]
        private GetRacksResult(
            ImmutableArray<Outputs.GetRacksFilterResult> filters,

            string id,

            int? limit,

            ImmutableArray<Outputs.GetRacksRackResult> racks)
        {
            Filters = filters;
            Id = id;
            Limit = limit;
            Racks = racks;
        }
    }
}
