// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Tenancy
{
    /// <summary>
    /// From the [official documentation](https://docs.netbox.dev/en/stable/features/contacts/#contactroles):
    /// 
    /// &gt; A contact role defines the relationship of a contact to an assigned object. For example, you might define roles for administrative, operational, and emergency contacts
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Netbox = Pulumi.Netbox;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var test = new Netbox.Tenancy.ContactRole("test", new()
    ///     {
    ///         Name = "test",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [NetboxResourceType("netbox:tenancy/contactRole:ContactRole")]
    public partial class ContactRole : global::Pulumi.CustomResource
    {
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("slug")]
        public Output<string> Slug { get; private set; } = null!;


        /// <summary>
        /// Create a ContactRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ContactRole(string name, ContactRoleArgs? args = null, CustomResourceOptions? options = null)
            : base("netbox:tenancy/contactRole:ContactRole", name, args ?? new ContactRoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ContactRole(string name, Input<string> id, ContactRoleState? state = null, CustomResourceOptions? options = null)
            : base("netbox:tenancy/contactRole:ContactRole", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/NatzkaLabsOpenSource/pulumi-netbox",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ContactRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ContactRole Get(string name, Input<string> id, ContactRoleState? state = null, CustomResourceOptions? options = null)
        {
            return new ContactRole(name, id, state, options);
        }
    }

    public sealed class ContactRoleArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("slug")]
        public Input<string>? Slug { get; set; }

        public ContactRoleArgs()
        {
        }
        public static new ContactRoleArgs Empty => new ContactRoleArgs();
    }

    public sealed class ContactRoleState : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("slug")]
        public Input<string>? Slug { get; set; }

        public ContactRoleState()
        {
        }
        public static new ContactRoleState Empty => new ContactRoleState();
    }
}
