// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as netbox from "@pulumi/netbox";
 *
 * const coreSw = netbox.dcim.getDeviceRole({
 *     name: "core-sw",
 * });
 * ```
 */
export function getDeviceRole(args: GetDeviceRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetDeviceRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbox:dcim/getDeviceRole:getDeviceRole", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDeviceRole.
 */
export interface GetDeviceRoleArgs {
    name: string;
}

/**
 * A collection of values returned by getDeviceRole.
 */
export interface GetDeviceRoleResult {
    readonly colorHex: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly slug: string;
    readonly tags: string[];
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as netbox from "@pulumi/netbox";
 *
 * const coreSw = netbox.dcim.getDeviceRole({
 *     name: "core-sw",
 * });
 * ```
 */
export function getDeviceRoleOutput(args: GetDeviceRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDeviceRoleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbox:dcim/getDeviceRole:getDeviceRole", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDeviceRole.
 */
export interface GetDeviceRoleOutputArgs {
    name: pulumi.Input<string>;
}
