// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getLocation(args?: GetLocationArgs, opts?: pulumi.InvokeOptions): Promise<GetLocationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbox:dcim/getLocation:getLocation", {
        "id": args.id,
        "name": args.name,
        "parentId": args.parentId,
        "siteId": args.siteId,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getLocation.
 */
export interface GetLocationArgs {
    /**
     * The ID of this resource.
     */
    id?: string;
    name?: string;
    parentId?: number;
    siteId?: number;
    slug?: string;
}

/**
 * A collection of values returned by getLocation.
 */
export interface GetLocationResult {
    readonly description: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly name?: string;
    readonly parentId: number;
    readonly siteId: number;
    readonly slug?: string;
    readonly status: string;
    readonly tenantId: number;
}
export function getLocationOutput(args?: GetLocationOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLocationResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbox:dcim/getLocation:getLocation", {
        "id": args.id,
        "name": args.name,
        "parentId": args.parentId,
        "siteId": args.siteId,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getLocation.
 */
export interface GetLocationOutputArgs {
    /**
     * The ID of this resource.
     */
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    parentId?: pulumi.Input<number>;
    siteId?: pulumi.Input<number>;
    slug?: pulumi.Input<string>;
}
