// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Per [the docs](https://netbox.readthedocs.io/en/stable/models/ipam/ipaddress/):
 *
 * > An IP address comprises a single host address (either IPv4 or IPv6) and its subnet mask. Its mask should match exactly how the IP address is configured on an interface in the real world.
 * Like a prefix, an IP address can optionally be assigned to a VRF (otherwise, it will appear in the "global" table). IP addresses are automatically arranged under parent prefixes within their respective VRFs according to the IP hierarchya.
 * > 
 * > Each IP address can also be assigned an operational status and a functional role. Statuses are hard-coded in NetBox and include the following:
 * > * Active
 * > * Reserved
 * > * Deprecated
 * > * DHCP
 * > * SLAAC (IPv6 Stateless Address Autoconfiguration)
 *
 * This resource will retrieve the next available IP address from a given prefix or IP range (specified by ID)
 *
 * ## Example Usage
 * ### Creating an IP in a prefix
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as netbox from "@natzkalabsopensource/pulumi-netbox";
 * import * as netbox from "@pulumi/netbox";
 *
 * const testPrefix = netbox.ipam.getPrefix({
 *     cidr: "10.0.0.0/24",
 * });
 * const testAvailableIpAddress = new netbox.ipam.AvailableIpAddress("testAvailableIpAddress", {prefixId: testPrefix.then(testPrefix => testPrefix.id)});
 * ```
 */
export class AvailableIpAddress extends pulumi.CustomResource {
    /**
     * Get an existing AvailableIpAddress resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AvailableIpAddressState, opts?: pulumi.CustomResourceOptions): AvailableIpAddress {
        return new AvailableIpAddress(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netbox:ipam/availableIpAddress:AvailableIpAddress';

    /**
     * Returns true if the given object is an instance of AvailableIpAddress.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AvailableIpAddress {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AvailableIpAddress.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Conflicts with `interfaceId` and `virtualMachineInterfaceId`.
     */
    public readonly deviceInterfaceId!: pulumi.Output<number | undefined>;
    public readonly dnsName!: pulumi.Output<string | undefined>;
    /**
     * Required when `objectType` is set.
     */
    public readonly interfaceId!: pulumi.Output<number | undefined>;
    public /*out*/ readonly ipAddress!: pulumi.Output<string>;
    /**
     * Exactly one of `prefixId` or `ipRangeId` must be given.
     */
    public readonly ipRangeId!: pulumi.Output<number | undefined>;
    /**
     * Valid values are `virtualization.vminterface` and `dcim.interface`. Required when `interfaceId` is set.
     */
    public readonly objectType!: pulumi.Output<string | undefined>;
    /**
     * Exactly one of `prefixId` or `ipRangeId` must be given.
     */
    public readonly prefixId!: pulumi.Output<number | undefined>;
    /**
     * Valid values are `loopback`, `secondary`, `anycast`, `vip`, `vrrp`, `hsrp`, `glbp` and `carp`.
     */
    public readonly role!: pulumi.Output<string | undefined>;
    /**
     * Valid values are `active`, `reserved`, `deprecated`, `dhcp` and `slaac`. Defaults to `active`.
     */
    public readonly status!: pulumi.Output<string | undefined>;
    public readonly tags!: pulumi.Output<string[] | undefined>;
    public readonly tenantId!: pulumi.Output<number | undefined>;
    /**
     * Conflicts with `interfaceId` and `deviceInterfaceId`.
     */
    public readonly virtualMachineInterfaceId!: pulumi.Output<number | undefined>;
    public readonly vrfId!: pulumi.Output<number | undefined>;

    /**
     * Create a AvailableIpAddress resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AvailableIpAddressArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AvailableIpAddressArgs | AvailableIpAddressState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AvailableIpAddressState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["deviceInterfaceId"] = state ? state.deviceInterfaceId : undefined;
            resourceInputs["dnsName"] = state ? state.dnsName : undefined;
            resourceInputs["interfaceId"] = state ? state.interfaceId : undefined;
            resourceInputs["ipAddress"] = state ? state.ipAddress : undefined;
            resourceInputs["ipRangeId"] = state ? state.ipRangeId : undefined;
            resourceInputs["objectType"] = state ? state.objectType : undefined;
            resourceInputs["prefixId"] = state ? state.prefixId : undefined;
            resourceInputs["role"] = state ? state.role : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
            resourceInputs["virtualMachineInterfaceId"] = state ? state.virtualMachineInterfaceId : undefined;
            resourceInputs["vrfId"] = state ? state.vrfId : undefined;
        } else {
            const args = argsOrState as AvailableIpAddressArgs | undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["deviceInterfaceId"] = args ? args.deviceInterfaceId : undefined;
            resourceInputs["dnsName"] = args ? args.dnsName : undefined;
            resourceInputs["interfaceId"] = args ? args.interfaceId : undefined;
            resourceInputs["ipRangeId"] = args ? args.ipRangeId : undefined;
            resourceInputs["objectType"] = args ? args.objectType : undefined;
            resourceInputs["prefixId"] = args ? args.prefixId : undefined;
            resourceInputs["role"] = args ? args.role : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
            resourceInputs["virtualMachineInterfaceId"] = args ? args.virtualMachineInterfaceId : undefined;
            resourceInputs["vrfId"] = args ? args.vrfId : undefined;
            resourceInputs["ipAddress"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AvailableIpAddress.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AvailableIpAddress resources.
 */
export interface AvailableIpAddressState {
    description?: pulumi.Input<string>;
    /**
     * Conflicts with `interfaceId` and `virtualMachineInterfaceId`.
     */
    deviceInterfaceId?: pulumi.Input<number>;
    dnsName?: pulumi.Input<string>;
    /**
     * Required when `objectType` is set.
     */
    interfaceId?: pulumi.Input<number>;
    ipAddress?: pulumi.Input<string>;
    /**
     * Exactly one of `prefixId` or `ipRangeId` must be given.
     */
    ipRangeId?: pulumi.Input<number>;
    /**
     * Valid values are `virtualization.vminterface` and `dcim.interface`. Required when `interfaceId` is set.
     */
    objectType?: pulumi.Input<string>;
    /**
     * Exactly one of `prefixId` or `ipRangeId` must be given.
     */
    prefixId?: pulumi.Input<number>;
    /**
     * Valid values are `loopback`, `secondary`, `anycast`, `vip`, `vrrp`, `hsrp`, `glbp` and `carp`.
     */
    role?: pulumi.Input<string>;
    /**
     * Valid values are `active`, `reserved`, `deprecated`, `dhcp` and `slaac`. Defaults to `active`.
     */
    status?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    tenantId?: pulumi.Input<number>;
    /**
     * Conflicts with `interfaceId` and `deviceInterfaceId`.
     */
    virtualMachineInterfaceId?: pulumi.Input<number>;
    vrfId?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a AvailableIpAddress resource.
 */
export interface AvailableIpAddressArgs {
    description?: pulumi.Input<string>;
    /**
     * Conflicts with `interfaceId` and `virtualMachineInterfaceId`.
     */
    deviceInterfaceId?: pulumi.Input<number>;
    dnsName?: pulumi.Input<string>;
    /**
     * Required when `objectType` is set.
     */
    interfaceId?: pulumi.Input<number>;
    /**
     * Exactly one of `prefixId` or `ipRangeId` must be given.
     */
    ipRangeId?: pulumi.Input<number>;
    /**
     * Valid values are `virtualization.vminterface` and `dcim.interface`. Required when `interfaceId` is set.
     */
    objectType?: pulumi.Input<string>;
    /**
     * Exactly one of `prefixId` or `ipRangeId` must be given.
     */
    prefixId?: pulumi.Input<number>;
    /**
     * Valid values are `loopback`, `secondary`, `anycast`, `vip`, `vrrp`, `hsrp`, `glbp` and `carp`.
     */
    role?: pulumi.Input<string>;
    /**
     * Valid values are `active`, `reserved`, `deprecated`, `dhcp` and `slaac`. Defaults to `active`.
     */
    status?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    tenantId?: pulumi.Input<number>;
    /**
     * Conflicts with `interfaceId` and `deviceInterfaceId`.
     */
    virtualMachineInterfaceId?: pulumi.Input<number>;
    vrfId?: pulumi.Input<number>;
}
