// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Netbox.Dcim.Outputs
{

    [OutputType]
    public sealed class GetLocationsFilterResult
    {
        /// <summary>
        /// The name of the field to filter on. Supported fields are: .
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The value to pass to the specified filter.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private GetLocationsFilterResult(
            string name,

            string value)
        {
            Name = name;
            Value = value;
        }
    }
}
