// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIpRanges(args?: GetIpRangesArgs, opts?: pulumi.InvokeOptions): Promise<GetIpRangesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netbox:index/getIpRanges:getIpRanges", {
        "filters": args.filters,
        "limit": args.limit,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpRanges.
 */
export interface GetIpRangesArgs {
    filters?: inputs.GetIpRangesFilter[];
    /**
     * Defaults to `1000`.
     */
    limit?: number;
}

/**
 * A collection of values returned by getIpRanges.
 */
export interface GetIpRangesResult {
    readonly filters?: outputs.GetIpRangesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipRanges: outputs.GetIpRangesIpRange[];
    /**
     * Defaults to `1000`.
     */
    readonly limit?: number;
}
export function getIpRangesOutput(args?: GetIpRangesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIpRangesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netbox:index/getIpRanges:getIpRanges", {
        "filters": args.filters,
        "limit": args.limit,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpRanges.
 */
export interface GetIpRangesOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetIpRangesFilterArgs>[]>;
    /**
     * Defaults to `1000`.
     */
    limit?: pulumi.Input<number>;
}
