// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ipam

import (
	"context"
	"reflect"

	"github.com/NatzkaLabsOpenSource/pulumi-netbox/sdk/go/netbox/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetIpAddresses(ctx *pulumi.Context, args *GetIpAddressesArgs, opts ...pulumi.InvokeOption) (*GetIpAddressesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetIpAddressesResult
	err := ctx.Invoke("netbox:ipam/getIpAddresses:getIpAddresses", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIpAddresses.
type GetIpAddressesArgs struct {
	Filters []GetIpAddressesFilter `pulumi:"filters"`
	// Defaults to `1000`.
	Limit *int `pulumi:"limit"`
}

// A collection of values returned by getIpAddresses.
type GetIpAddressesResult struct {
	Filters []GetIpAddressesFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id          string                    `pulumi:"id"`
	IpAddresses []GetIpAddressesIpAddress `pulumi:"ipAddresses"`
	// Defaults to `1000`.
	Limit *int `pulumi:"limit"`
}

func GetIpAddressesOutput(ctx *pulumi.Context, args GetIpAddressesOutputArgs, opts ...pulumi.InvokeOption) GetIpAddressesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetIpAddressesResultOutput, error) {
			args := v.(GetIpAddressesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("netbox:ipam/getIpAddresses:getIpAddresses", args, GetIpAddressesResultOutput{}, options).(GetIpAddressesResultOutput), nil
		}).(GetIpAddressesResultOutput)
}

// A collection of arguments for invoking getIpAddresses.
type GetIpAddressesOutputArgs struct {
	Filters GetIpAddressesFilterArrayInput `pulumi:"filters"`
	// Defaults to `1000`.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
}

func (GetIpAddressesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIpAddressesArgs)(nil)).Elem()
}

// A collection of values returned by getIpAddresses.
type GetIpAddressesResultOutput struct{ *pulumi.OutputState }

func (GetIpAddressesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIpAddressesResult)(nil)).Elem()
}

func (o GetIpAddressesResultOutput) ToGetIpAddressesResultOutput() GetIpAddressesResultOutput {
	return o
}

func (o GetIpAddressesResultOutput) ToGetIpAddressesResultOutputWithContext(ctx context.Context) GetIpAddressesResultOutput {
	return o
}

func (o GetIpAddressesResultOutput) Filters() GetIpAddressesFilterArrayOutput {
	return o.ApplyT(func(v GetIpAddressesResult) []GetIpAddressesFilter { return v.Filters }).(GetIpAddressesFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetIpAddressesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIpAddressesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetIpAddressesResultOutput) IpAddresses() GetIpAddressesIpAddressArrayOutput {
	return o.ApplyT(func(v GetIpAddressesResult) []GetIpAddressesIpAddress { return v.IpAddresses }).(GetIpAddressesIpAddressArrayOutput)
}

// Defaults to `1000`.
func (o GetIpAddressesResultOutput) Limit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetIpAddressesResult) *int { return v.Limit }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIpAddressesResultOutput{})
}
